// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricRequest contains the client's configuration for metric streaming
type MetricRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntervalSeconds int32                  `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // N: collection interval in seconds
	WindowSeconds   int32                  `protobuf:"varint,2,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`       // M: aggregation window in seconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_proto_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *MetricRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *MetricRequest) GetWindowSeconds() int32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

// SystemMetrics is the top-level message containing all metric categories
type SystemMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                    // Unix timestamp in nanoseconds
	IntervalSeconds int32                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // N: the collection interval used
	WindowSeconds   int32                  `protobuf:"varint,3,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`       // M: the aggregation window used
	Load            *LoadMetrics           `protobuf:"bytes,4,opt,name=load,proto3" json:"load,omitempty"`                                               // System load average
	Cpu             *CpuMetrics            `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`                                                 // CPU usage metrics
	DiskIo          *DiskIOMetrics         `protobuf:"bytes,6,opt,name=disk_io,json=diskIo,proto3" json:"disk_io,omitempty"`                             // Disk I/O metrics
	Filesystem      *FilesystemUsage       `protobuf:"bytes,7,opt,name=filesystem,proto3" json:"filesystem,omitempty"`                                   // Filesystem usage metrics
	Network         *NetworkMetrics        `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`                                         // Network connection statistics
	TopTalkers      *TopTalkers            `protobuf:"bytes,9,opt,name=top_talkers,json=topTalkers,proto3" json:"top_talkers,omitempty"`                 // Network top talkers
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_proto_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{1}
}

func (x *SystemMetrics) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SystemMetrics) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *SystemMetrics) GetWindowSeconds() int32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *SystemMetrics) GetLoad() *LoadMetrics {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *SystemMetrics) GetCpu() *CpuMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemMetrics) GetDiskIo() *DiskIOMetrics {
	if x != nil {
		return x.DiskIo
	}
	return nil
}

func (x *SystemMetrics) GetFilesystem() *FilesystemUsage {
	if x != nil {
		return x.Filesystem
	}
	return nil
}

func (x *SystemMetrics) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *SystemMetrics) GetTopTalkers() *TopTalkers {
	if x != nil {
		return x.TopTalkers
	}
	return nil
}

// LoadMetrics represents system load average
type LoadMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load1         float64                `protobuf:"fixed64,1,opt,name=load1,proto3" json:"load1,omitempty"` // Load average over 1 minute
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMetrics) Reset() {
	*x = LoadMetrics{}
	mi := &file_proto_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMetrics) ProtoMessage() {}

func (x *LoadMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMetrics.ProtoReflect.Descriptor instead.
func (*LoadMetrics) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{2}
}

func (x *LoadMetrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

// CpuMetrics represents CPU usage percentages
type CpuMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PercentUser   float64                `protobuf:"fixed64,1,opt,name=percent_user,json=percentUser,proto3" json:"percent_user,omitempty"`       // % user time
	PercentSystem float64                `protobuf:"fixed64,2,opt,name=percent_system,json=percentSystem,proto3" json:"percent_system,omitempty"` // % system time
	PercentIdle   float64                `protobuf:"fixed64,3,opt,name=percent_idle,json=percentIdle,proto3" json:"percent_idle,omitempty"`       // % idle time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_proto_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{3}
}

func (x *CpuMetrics) GetPercentUser() float64 {
	if x != nil {
		return x.PercentUser
	}
	return 0
}

func (x *CpuMetrics) GetPercentSystem() float64 {
	if x != nil {
		return x.PercentSystem
	}
	return 0
}

func (x *CpuMetrics) GetPercentIdle() float64 {
	if x != nil {
		return x.PercentIdle
	}
	return 0
}

// DiskIOMetrics represents disk I/O statistics
type DiskIOMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tps   float64                `protobuf:"fixed64,1,opt,name=tps,proto3" json:"tps,omitempty"` // Transactions per second
	// double kb_read_per_sec = 2;  // KB/s read
	// double kb_write_per_sec = 3; // KB/s write
	KbTotalPerSec float64 `protobuf:"fixed64,4,opt,name=kb_total_per_sec,json=kbTotalPerSec,proto3" json:"kb_total_per_sec,omitempty"` // Total KB/s
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskIOMetrics) Reset() {
	*x = DiskIOMetrics{}
	mi := &file_proto_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIOMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIOMetrics) ProtoMessage() {}

func (x *DiskIOMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIOMetrics.ProtoReflect.Descriptor instead.
func (*DiskIOMetrics) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{4}
}

func (x *DiskIOMetrics) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *DiskIOMetrics) GetKbTotalPerSec() float64 {
	if x != nil {
		return x.KbTotalPerSec
	}
	return 0
}

// FilesystemUsage represents usage for a single mount point
type FilesystemUsage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MountPoint string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"` // Mount point path
	Filesystem string                 `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`                   // Filesystem device
	// string type = 3;             // Filesystem type (ext4, xfs, etc.)
	// double mb_total = 4;         // Total size in MB
	// double mb_used = 5;          // Used space in MB
	// double mb_available = 6;     // Available space in MB
	PercentUsed   float64 `protobuf:"fixed64,7,opt,name=percent_used,json=percentUsed,proto3" json:"percent_used,omitempty"`    // Usage percentage
	InodePercent  float64 `protobuf:"fixed64,8,opt,name=inode_percent,json=inodePercent,proto3" json:"inode_percent,omitempty"` // Inode usage percentage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemUsage) Reset() {
	*x = FilesystemUsage{}
	mi := &file_proto_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemUsage) ProtoMessage() {}

func (x *FilesystemUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemUsage.ProtoReflect.Descriptor instead.
func (*FilesystemUsage) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{5}
}

func (x *FilesystemUsage) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *FilesystemUsage) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *FilesystemUsage) GetPercentUsed() float64 {
	if x != nil {
		return x.PercentUsed
	}
	return 0
}

func (x *FilesystemUsage) GetInodePercent() float64 {
	if x != nil {
		return x.InodePercent
	}
	return 0
}

// NetworkMetrics represents network connection statistics
type NetworkMetrics struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ListeningSockets       int32                  `protobuf:"varint,1,opt,name=listening_sockets,json=listeningSockets,proto3" json:"listening_sockets,omitempty"`                   // Number of listening TCP sockets
	EstablishedConnections int32                  `protobuf:"varint,2,opt,name=established_connections,json=establishedConnections,proto3" json:"established_connections,omitempty"` // Number of established TCP connections
	TimeWaitSockets        int32                  `protobuf:"varint,3,opt,name=time_wait_sockets,json=timeWaitSockets,proto3" json:"time_wait_sockets,omitempty"`                    // Number of TIME_WAIT sockets
	CloseWaitSockets       int32                  `protobuf:"varint,4,opt,name=close_wait_sockets,json=closeWaitSockets,proto3" json:"close_wait_sockets,omitempty"`                 // Number of CLOSE_WAIT sockets
	FinWaitSockets         int32                  `protobuf:"varint,5,opt,name=fin_wait_sockets,json=finWaitSockets,proto3" json:"fin_wait_sockets,omitempty"`                       // Number of FIN_WAIT sockets
	SynSentSockets         int32                  `protobuf:"varint,6,opt,name=syn_sent_sockets,json=synSentSockets,proto3" json:"syn_sent_sockets,omitempty"`                       // Number of SYN_SENT sockets
	UdpSockets             int32                  `protobuf:"varint,7,opt,name=udp_sockets,json=udpSockets,proto3" json:"udp_sockets,omitempty"`                                     // Number of UDP sockets
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_proto_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkMetrics) GetListeningSockets() int32 {
	if x != nil {
		return x.ListeningSockets
	}
	return 0
}

func (x *NetworkMetrics) GetEstablishedConnections() int32 {
	if x != nil {
		return x.EstablishedConnections
	}
	return 0
}

func (x *NetworkMetrics) GetTimeWaitSockets() int32 {
	if x != nil {
		return x.TimeWaitSockets
	}
	return 0
}

func (x *NetworkMetrics) GetCloseWaitSockets() int32 {
	if x != nil {
		return x.CloseWaitSockets
	}
	return 0
}

func (x *NetworkMetrics) GetFinWaitSockets() int32 {
	if x != nil {
		return x.FinWaitSockets
	}
	return 0
}

func (x *NetworkMetrics) GetSynSentSockets() int32 {
	if x != nil {
		return x.SynSentSockets
	}
	return 0
}

func (x *NetworkMetrics) GetUdpSockets() int32 {
	if x != nil {
		return x.UdpSockets
	}
	return 0
}

// ConnectionStat represents a single network connection
type ConnectionStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`                                // Protocol (tcp, tcp6, udp, udp6)
	LocalAddress  string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`    // Local address:port
	RemoteAddress string                 `protobuf:"bytes,3,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"` // Remote address:port
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                      // Connection state (LISTEN, ESTABLISHED, etc.)
	Pid           uint32                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`                                         // Process ID (0 if not available)
	ProcessName   string                 `protobuf:"bytes,6,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`       // Process name (empty if not available)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStat) Reset() {
	*x = ConnectionStat{}
	mi := &file_proto_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStat) ProtoMessage() {}

func (x *ConnectionStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStat.ProtoReflect.Descriptor instead.
func (*ConnectionStat) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectionStat) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ConnectionStat) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *ConnectionStat) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *ConnectionStat) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ConnectionStat) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ConnectionStat) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

// TopTalkers represents network traffic by protocol and connection
type TopTalkers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByProtocol    []*ProtocolTraffic     `protobuf:"bytes,1,rep,name=by_protocol,json=byProtocol,proto3" json:"by_protocol,omitempty"`       // Traffic grouped by protocol
	ByConnection  []*ConnectionTraffic   `protobuf:"bytes,2,rep,name=by_connection,json=byConnection,proto3" json:"by_connection,omitempty"` // Traffic grouped by connection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopTalkers) Reset() {
	*x = TopTalkers{}
	mi := &file_proto_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopTalkers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopTalkers) ProtoMessage() {}

func (x *TopTalkers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopTalkers.ProtoReflect.Descriptor instead.
func (*TopTalkers) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{8}
}

func (x *TopTalkers) GetByProtocol() []*ProtocolTraffic {
	if x != nil {
		return x.ByProtocol
	}
	return nil
}

func (x *TopTalkers) GetByConnection() []*ConnectionTraffic {
	if x != nil {
		return x.ByConnection
	}
	return nil
}

// ProtocolTraffic represents traffic statistics for a protocol
type ProtocolTraffic struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Protocol        string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`                                       // Protocol name (tcp, udp, etc.)
	BytesSent       int64                  `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`                   // Bytes sent in window
	BytesReceived   int64                  `protobuf:"varint,3,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`       // Bytes received in window
	PacketsSent     int64                  `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`             // Packets sent in window
	PacketsReceived int64                  `protobuf:"varint,5,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"` // Packets received in window
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProtocolTraffic) Reset() {
	*x = ProtocolTraffic{}
	mi := &file_proto_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolTraffic) ProtoMessage() {}

func (x *ProtocolTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolTraffic.ProtoReflect.Descriptor instead.
func (*ProtocolTraffic) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{9}
}

func (x *ProtocolTraffic) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolTraffic) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ProtocolTraffic) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *ProtocolTraffic) GetPacketsSent() int64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *ProtocolTraffic) GetPacketsReceived() int64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

// ConnectionTraffic represents traffic for a specific connection
type ConnectionTraffic struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Protocol        string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`                                       // Protocol (tcp, udp)
	LocalAddress    string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`           // Local address:port
	RemoteAddress   string                 `protobuf:"bytes,3,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`        // Remote address:port
	BytesSent       int64                  `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`                   // Bytes sent in window
	BytesReceived   int64                  `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`       // Bytes received in window
	PacketsSent     int64                  `protobuf:"varint,6,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`             // Packets sent in window
	PacketsReceived int64                  `protobuf:"varint,7,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"` // Packets received in window
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectionTraffic) Reset() {
	*x = ConnectionTraffic{}
	mi := &file_proto_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionTraffic) ProtoMessage() {}

func (x *ConnectionTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionTraffic.ProtoReflect.Descriptor instead.
func (*ConnectionTraffic) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectionTraffic) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ConnectionTraffic) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *ConnectionTraffic) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *ConnectionTraffic) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *ConnectionTraffic) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *ConnectionTraffic) GetPacketsSent() int64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *ConnectionTraffic) GetPacketsReceived() int64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

var File_proto_stream_proto protoreflect.FileDescriptor

const file_proto_stream_proto_rawDesc = "" +
	"\n" +
	"\x12proto/stream.proto\x12\x05proto\"a\n" +
	"\rMetricRequest\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\x12%\n" +
	"\x0ewindow_seconds\x18\x02 \x01(\x05R\rwindowSeconds\"\x98\x03\n" +
	"\rSystemMetrics\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\x12%\n" +
	"\x0ewindow_seconds\x18\x03 \x01(\x05R\rwindowSeconds\x12&\n" +
	"\x04load\x18\x04 \x01(\v2\x12.proto.LoadMetricsR\x04load\x12#\n" +
	"\x03cpu\x18\x05 \x01(\v2\x11.proto.CpuMetricsR\x03cpu\x12-\n" +
	"\adisk_io\x18\x06 \x01(\v2\x14.proto.DiskIOMetricsR\x06diskIo\x126\n" +
	"\n" +
	"filesystem\x18\a \x01(\v2\x16.proto.FilesystemUsageR\n" +
	"filesystem\x12/\n" +
	"\anetwork\x18\b \x01(\v2\x15.proto.NetworkMetricsR\anetwork\x122\n" +
	"\vtop_talkers\x18\t \x01(\v2\x11.proto.TopTalkersR\n" +
	"topTalkers\"#\n" +
	"\vLoadMetrics\x12\x14\n" +
	"\x05load1\x18\x01 \x01(\x01R\x05load1\"y\n" +
	"\n" +
	"CpuMetrics\x12!\n" +
	"\fpercent_user\x18\x01 \x01(\x01R\vpercentUser\x12%\n" +
	"\x0epercent_system\x18\x02 \x01(\x01R\rpercentSystem\x12!\n" +
	"\fpercent_idle\x18\x03 \x01(\x01R\vpercentIdle\"J\n" +
	"\rDiskIOMetrics\x12\x10\n" +
	"\x03tps\x18\x01 \x01(\x01R\x03tps\x12'\n" +
	"\x10kb_total_per_sec\x18\x04 \x01(\x01R\rkbTotalPerSec\"\x9a\x01\n" +
	"\x0fFilesystemUsage\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\tR\n" +
	"filesystem\x12!\n" +
	"\fpercent_used\x18\a \x01(\x01R\vpercentUsed\x12#\n" +
	"\rinode_percent\x18\b \x01(\x01R\finodePercent\"\xc5\x02\n" +
	"\x0eNetworkMetrics\x12+\n" +
	"\x11listening_sockets\x18\x01 \x01(\x05R\x10listeningSockets\x127\n" +
	"\x17established_connections\x18\x02 \x01(\x05R\x16establishedConnections\x12*\n" +
	"\x11time_wait_sockets\x18\x03 \x01(\x05R\x0ftimeWaitSockets\x12,\n" +
	"\x12close_wait_sockets\x18\x04 \x01(\x05R\x10closeWaitSockets\x12(\n" +
	"\x10fin_wait_sockets\x18\x05 \x01(\x05R\x0efinWaitSockets\x12(\n" +
	"\x10syn_sent_sockets\x18\x06 \x01(\x05R\x0esynSentSockets\x12\x1f\n" +
	"\vudp_sockets\x18\a \x01(\x05R\n" +
	"udpSockets\"\xc3\x01\n" +
	"\x0eConnectionStat\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12#\n" +
	"\rlocal_address\x18\x02 \x01(\tR\flocalAddress\x12%\n" +
	"\x0eremote_address\x18\x03 \x01(\tR\rremoteAddress\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\rR\x03pid\x12!\n" +
	"\fprocess_name\x18\x06 \x01(\tR\vprocessName\"\x84\x01\n" +
	"\n" +
	"TopTalkers\x127\n" +
	"\vby_protocol\x18\x01 \x03(\v2\x16.proto.ProtocolTrafficR\n" +
	"byProtocol\x12=\n" +
	"\rby_connection\x18\x02 \x03(\v2\x18.proto.ConnectionTrafficR\fbyConnection\"\xc1\x01\n" +
	"\x0fProtocolTraffic\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x03 \x01(\x03R\rbytesReceived\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x03R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\x05 \x01(\x03R\x0fpacketsReceived\"\x8f\x02\n" +
	"\x11ConnectionTraffic\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12#\n" +
	"\rlocal_address\x18\x02 \x01(\tR\flocalAddress\x12%\n" +
	"\x0eremote_address\x18\x03 \x01(\tR\rremoteAddress\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x03R\rbytesReceived\x12!\n" +
	"\fpackets_sent\x18\x06 \x01(\x03R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\a \x01(\x03R\x0fpacketsReceived2P\n" +
	"\rStreamService\x12?\n" +
	"\rStreamMetrics\x12\x14.proto.MetricRequest\x1a\x14.proto.SystemMetrics\"\x000\x01B\x1cZ\x1agolang-project.local/protob\x06proto3"

var (
	file_proto_stream_proto_rawDescOnce sync.Once
	file_proto_stream_proto_rawDescData []byte
)

func file_proto_stream_proto_rawDescGZIP() []byte {
	file_proto_stream_proto_rawDescOnce.Do(func() {
		file_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)))
	})
	return file_proto_stream_proto_rawDescData
}

var file_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_stream_proto_goTypes = []any{
	(*MetricRequest)(nil),     // 0: proto.MetricRequest
	(*SystemMetrics)(nil),     // 1: proto.SystemMetrics
	(*LoadMetrics)(nil),       // 2: proto.LoadMetrics
	(*CpuMetrics)(nil),        // 3: proto.CpuMetrics
	(*DiskIOMetrics)(nil),     // 4: proto.DiskIOMetrics
	(*FilesystemUsage)(nil),   // 5: proto.FilesystemUsage
	(*NetworkMetrics)(nil),    // 6: proto.NetworkMetrics
	(*ConnectionStat)(nil),    // 7: proto.ConnectionStat
	(*TopTalkers)(nil),        // 8: proto.TopTalkers
	(*ProtocolTraffic)(nil),   // 9: proto.ProtocolTraffic
	(*ConnectionTraffic)(nil), // 10: proto.ConnectionTraffic
}
var file_proto_stream_proto_depIdxs = []int32{
	2,  // 0: proto.SystemMetrics.load:type_name -> proto.LoadMetrics
	3,  // 1: proto.SystemMetrics.cpu:type_name -> proto.CpuMetrics
	4,  // 2: proto.SystemMetrics.disk_io:type_name -> proto.DiskIOMetrics
	5,  // 3: proto.SystemMetrics.filesystem:type_name -> proto.FilesystemUsage
	6,  // 4: proto.SystemMetrics.network:type_name -> proto.NetworkMetrics
	8,  // 5: proto.SystemMetrics.top_talkers:type_name -> proto.TopTalkers
	9,  // 6: proto.TopTalkers.by_protocol:type_name -> proto.ProtocolTraffic
	10, // 7: proto.TopTalkers.by_connection:type_name -> proto.ConnectionTraffic
	0,  // 8: proto.StreamService.StreamMetrics:input_type -> proto.MetricRequest
	1,  // 9: proto.StreamService.StreamMetrics:output_type -> proto.SystemMetrics
	9,  // [9:10] is the sub-list for method output_type
	8,  // [8:9] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_stream_proto_init() }
func file_proto_stream_proto_init() {
	if File_proto_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stream_proto_goTypes,
		DependencyIndexes: file_proto_stream_proto_depIdxs,
		MessageInfos:      file_proto_stream_proto_msgTypes,
	}.Build()
	File_proto_stream_proto = out.File
	file_proto_stream_proto_goTypes = nil
	file_proto_stream_proto_depIdxs = nil
}
